//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoystickCurves.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::JoystickCurves.ProfileManager Profiles {
            get {
                return ((global::JoystickCurves.ProfileManager)(this["Profiles"]));
            }
            set {
                this["Profiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::JoystickCurves.Profile CurrentProfile {
            get {
                return ((global::JoystickCurves.Profile)(this["CurrentProfile"]));
            }
            set {
                this["CurrentProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterVirtualJoystick {
            get {
                return ((string)(this["TesterVirtualJoystick"]));
            }
            set {
                this["TesterVirtualJoystick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterPhysicalJoystick {
            get {
                return ((string)(this["TesterPhysicalJoystick"]));
            }
            set {
                this["TesterPhysicalJoystick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterVirtualJoystickX {
            get {
                return ((string)(this["TesterVirtualJoystickX"]));
            }
            set {
                this["TesterVirtualJoystickX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterVirtualJoystickY {
            get {
                return ((string)(this["TesterVirtualJoystickY"]));
            }
            set {
                this["TesterVirtualJoystickY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterVirtualJoystickRZ {
            get {
                return ((string)(this["TesterVirtualJoystickRZ"]));
            }
            set {
                this["TesterVirtualJoystickRZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterPhysicalJoystickX {
            get {
                return ((string)(this["TesterPhysicalJoystickX"]));
            }
            set {
                this["TesterPhysicalJoystickX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterPhysicalJoystickY {
            get {
                return ((string)(this["TesterPhysicalJoystickY"]));
            }
            set {
                this["TesterPhysicalJoystickY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TesterPhysicalJoystickRZ {
            get {
                return ((string)(this["TesterPhysicalJoystickRZ"]));
            }
            set {
                this["TesterPhysicalJoystickRZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool generalMinimizeOnClose {
            get {
                return ((bool)(this["generalMinimizeOnClose"]));
            }
            set {
                this["generalMinimizeOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool generalAutoStart {
            get {
                return ((bool)(this["generalAutoStart"]));
            }
            set {
                this["generalAutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool generalStartMinimized {
            get {
                return ((bool)(this["generalStartMinimized"]));
            }
            set {
                this["generalStartMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool globalSteamEnable {
            get {
                return ((bool)(this["globalSteamEnable"]));
            }
            set {
                this["globalSteamEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string steamLogin {
            get {
                return ((string)(this["steamLogin"]));
            }
            set {
                this["steamLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string steamPassword {
            get {
                return ((string)(this["steamPassword"]));
            }
            set {
                this["steamPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool saitekX52ProEnable {
            get {
                return ((bool)(this["saitekX52ProEnable"]));
            }
            set {
                this["saitekX52ProEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string steamToken {
            get {
                return ((string)(this["steamToken"]));
            }
            set {
                this["steamToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::JoystickCurves.HotKeys hotKeys {
            get {
                return ((global::JoystickCurves.HotKeys)(this["hotKeys"]));
            }
            set {
                this["hotKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool warThunderTrackAircraft {
            get {
                return ((bool)(this["warThunderTrackAircraft"]));
            }
            set {
                this["warThunderTrackAircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool exclusiveDirectInput {
            get {
                return ((bool)(this["exclusiveDirectInput"]));
            }
            set {
                this["exclusiveDirectInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool enableJoystickServer {
            get {
                return ((bool)(this["enableJoystickServer"]));
            }
            set {
                this["enableJoystickServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54545")]
        public string joystickServerPort {
            get {
                return ((string)(this["joystickServerPort"]));
            }
            set {
                this["joystickServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool globalSaveOnExit {
            get {
                return ((bool)(this["globalSaveOnExit"]));
            }
            set {
                this["globalSaveOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool globalAskSave {
            get {
                return ((bool)(this["globalAskSave"]));
            }
            set {
                this["globalAskSave"] = value;
            }
        }
    }
}
